package transfer_service

import "github.com/ERONIS/wb-service/internal/feature/transfer/service/publication"

type PublicationPlanningMember = publication.PublicationPlanningMember
type PublicationPlanningGroup = publication.PublicationPlanningGroup
type PublicationPlanningSource = publication.PublicationPlanningSource
type PublicationProjectionStatus = publication.PublicationProjectionStatus
type PublicationPlannedGroup = publication.PublicationPlannedGroup
type PublicationPlannedItem = publication.PublicationPlannedItem
type ApplyPublicationPlanResultCommand = publication.ApplyPublicationPlanResultCommand
type PublicationPlanResultRepository = publication.PublicationPlanResultRepository
type PublicationPlanResultApplier = publication.PublicationPlanResultApplier
type PublicationTerminalItem = publication.PublicationTerminalItem
type ApplyPublicationActionResultCommand = publication.ApplyPublicationActionResultCommand
type ApplyPublicationMediaResultCommand = publication.ApplyPublicationMediaResultCommand
type CorrectPublicationItemResultCommand = publication.CorrectPublicationItemResultCommand
type PublicationExecutionResultRepository = publication.PublicationExecutionResultRepository
type PublicationExecutionResultApplier = publication.PublicationExecutionResultApplier

const (
	MaxPublicationPlanningPageSize = publication.MaxPublicationPlanningPageSize

	PublicationProjectionRunning  = publication.PublicationProjectionRunning
	PublicationProjectionSkipped  = publication.PublicationProjectionSkipped
	PublicationProjectionRejected = publication.PublicationProjectionRejected
)

func NewPublicationPlanResultApplier(
	repository PublicationPlanResultRepository,
) *PublicationPlanResultApplier {
	return publication.NewPublicationPlanResultApplier(repository)
}

func NewPublicationExecutionResultApplier(
	repository PublicationExecutionResultRepository,
) *PublicationExecutionResultApplier {
	return publication.NewPublicationExecutionResultApplier(repository)
}
